# This is a basic workflow to help you get started with the Run Jtest action.
name: Jtest with Gradle

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ upload_Sarif_report ]
  pull_request:
    branches: [ upload_Sarif_report ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    name: Analyze project with Jtest
    
    permissions:
      # required for all workflows
      security-events: write
      
    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v6
      #uses: actions/checkout@v5     
      #uses: actions/checkout@v6
      with:
    # Repository name with owner. For example, actions/checkout
       #Default: ${{ github.repository }}
       #path: d:\workspace\github\demo
       #path: d:/workspace/github/demo
       #path: .
       #ref: ${{ github.workspace }}
       #ref: "d:/workspace/github/demo"
       #ref: ${{ github.repository }}
       ref: upload_Sarif_report
       #workspace: "d:/workspace/github/demo"
       #set-safe-directory: 'd:/workspace/github/demo2'
       #set-safe-directory: 'C:/actions-runner2331_jtest2025.2.2/_work/jtest_demo/jtest_demo'
       #repository: stingerBoo/jtest_demo
       #token: ${{ secrets.GIT_TECHDEPLOY_TOKEN }}
       #path: infrastructure-helm
      # === IMPORTANT ===
      # more likely fetch-depth 0 does not change timestamp of te files
      # =====
       fetch-depth: 0  
       
# Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v4
      with:
        #sarif_file: reports/report.sarif # reports is a default location for reports directory
        sarif_file: c:/actions-runner2331_jtest2025.2.2/_work/jtest_demo/jtest_demo/reports/reportCustomer_update.sarif
        category: parasoft-jtest-SoftCode4
        #checkout_path: c:/actions-runner2331_jtest2025.2.2/_work/jtest_demo/jtest_demo        
        #matrix: null
        wait-for-processing: true

  
