# This is a basic workflow to help you get started with the Run Jtest action.
name: Jtest with Gradle

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ container_test1 ]
  pull_request:
    branches: [ container_test1 ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    name: Analyze project with Jtest
    
    permissions:
      # required for all workflows
      security-events: write
      
    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v6
      #uses: actions/checkout@v5     
      #uses: actions/checkout@v6
      with:
       ref: container_test1
       fetch-depth: 0 
       
    - name: Run Container
      # -v /f/docker/jTest/2025.2/demo:/home/parasoft/example
      # below github.workspace is taken from location of self-hosted runner
      # -v "${{ github.workspace }}:/home/parasoft/example"
      run: >
       docker run
       --rm 
       -v "${{ github.workspace }}:/home/parasoft/example"
       --name c_jtest2025.2 jtest2025.2
       jtestcli -data demo.data.json -config "builtin://Recommended Rules"
      shell: cmd

      # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v4
      with:
        #sarif_file: reports/report.sarif # reports is a default location for reports directory
        sarif_file: "${{ github.workspace }}/reports/reportRuleABC.sarif"
        wait-for-processing: true
